config/routes.rb
Rails.application.routes.draw do
  get 'disclaimer', to: 'site#disclaimer'
  get 'about', to: 'site#about'

  mount Lockup::Engine, at: '/lockup'

  resources :unit_trust_entries do
    collection do
      get :fetch
    end
  end

  resources :unit_trusts
  get '', to: 'utf#all'
  get 'detail/:id', to: 'utf#detail'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/unit_trust.rb
class UnitTrust < ApplicationRecord
end

app/models/unit_trust_entry.rb
class UnitTrustEntry < ApplicationRecord
  belongs_to :unit_trust
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  skip_before_action :check_for_lockup, raise: false
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def disclaimer
  end

  def about
  end
end

app/controllers/unit_trust_entries_controller.rb
load 'lib/utf_fetcher.rb'

class UnitTrustEntriesController < ApplicationController
  before_action :set_unit_trust_entry, only: [:show, :edit, :update, :destroy]
  before_action :check_for_lockup

  # GET /unit_trust_entries
  # GET /unit_trust_entries.json
  def index
    @unit_trust_entries = UnitTrustEntry.all
  end

  # GET /unit_trust_entries/1
  # GET /unit_trust_entries/1.json
  def show
  end

  # GET /unit_trust_entries/new
  def new
    @unit_trust_entry = UnitTrustEntry.new
  end

  # GET /unit_trust_entries/1/edit
  def edit
  end

  # POST /unit_trust_entries
  # POST /unit_trust_entries.json
  def create
    @unit_trust_entry = UnitTrustEntry.new(unit_trust_entry_params)

    respond_to do |format|
      if @unit_trust_entry.save
        format.html { redirect_to @unit_trust_entry, notice: 'Unit trust entry was successfully created.' }
        format.json { render :show, status: :created, location: @unit_trust_entry }
      else
        format.html { render :new }
        format.json { render json: @unit_trust_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_trust_entries/1
  # PATCH/PUT /unit_trust_entries/1.json
  def update
    respond_to do |format|
      if @unit_trust_entry.update(unit_trust_entry_params)
        format.html { redirect_to @unit_trust_entry, notice: 'Unit trust entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit_trust_entry }
      else
        format.html { render :edit }
        format.json { render json: @unit_trust_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_trust_entries/1
  # DELETE /unit_trust_entries/1.json
  def destroy
    @unit_trust_entry.destroy
    respond_to do |format|
      format.html { redirect_to unit_trust_entries_url, notice: 'Unit trust entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # GET /unit_trust_entries/fetch

  def fetch
    UtfFetcher.save_new_entries

    respond_to do |format|
      format.html { redirect_to unit_trust_entries_url, notice: 'woot' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_trust_entry
      @unit_trust_entry = UnitTrustEntry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_trust_entry_params
      params.require(:unit_trust_entry).permit(:date, :value, :last_day, :last_30_days, :last_90_days, :last_12_months, :unit_trust_id)
    end
end

app/controllers/unit_trusts_controller.rb
class UnitTrustsController < ApplicationController
  before_action :set_unit_trust, only: [:show, :edit, :update, :destroy]
  before_action :check_for_lockup

  # GET /unit_trusts
  # GET /unit_trusts.json
  def index
    @unit_trusts = UnitTrust.all
  end

  # GET /unit_trusts/1
  # GET /unit_trusts/1.json
  def show
  end

  # GET /unit_trusts/new
  def new
    @unit_trust = UnitTrust.new
  end

  # GET /unit_trusts/1/edit
  def edit
  end

  # POST /unit_trusts
  # POST /unit_trusts.json
  def create
    @unit_trust = UnitTrust.new(unit_trust_params)

    respond_to do |format|
      if @unit_trust.save
        format.html { redirect_to @unit_trust, notice: 'Unit trust was successfully created.' }
        format.json { render :show, status: :created, location: @unit_trust }
      else
        format.html { render :new }
        format.json { render json: @unit_trust.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unit_trusts/1
  # PATCH/PUT /unit_trusts/1.json
  def update
    respond_to do |format|
      if @unit_trust.update(unit_trust_params)
        format.html { redirect_to @unit_trust, notice: 'Unit trust was successfully updated.' }
        format.json { render :show, status: :ok, location: @unit_trust }
      else
        format.html { render :edit }
        format.json { render json: @unit_trust.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unit_trusts/1
  # DELETE /unit_trusts/1.json
  def destroy
    @unit_trust.destroy
    respond_to do |format|
      format.html { redirect_to unit_trusts_url, notice: 'Unit trust was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit_trust
      @unit_trust = UnitTrust.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def unit_trust_params
      params.require(:unit_trust).permit(:name, :description, :deposit_time, :color)
    end
end

app/controllers/utf_controller.rb
class UtfController < ApplicationController
  def all
    @last_update = UnitTrustEntry.last.date

    # Getting latest values for each Unit Trust
    latest_ids = UnitTrustEntry.group(:unit_trust_id).maximum(:id).values
    @list = UnitTrustEntry.where(id: latest_ids)

    # Getting a list for all Unit Trusts
    last_period = UnitTrustEntry
                  .where('date BETWEEN ? AND ?', Date.today - 15, Date.today)
                  .order(date: :desc)
                  .group(:date, :unit_trust_id)
                  .reverse

    @graph_data = []
    UnitTrust.all.each do |e|
      item = { name: e.name }

      values = last_period.select { |i| i.unit_trust_id == e.id }
      item[:values] = values.map(&:last_day)
      item[:dates] = values.map(&:date)
      item[:color] = e.color

      @graph_data << item
    end
  end

  def detail
    @unit_trust = UnitTrust.find(params[:id])
    @list = UnitTrustEntry.where(unit_trust_id: params[:id]).order(date: :desc)
    @graph_data = @list.reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fci_helper.rb
module FciHelper

  def self.format_number(number)
    number.tr! '.', ''
    number.tr! ',', '.'

    reg = %r{\((.*?)\)}
    number = number.match(reg).nil? ? number : "-#{number.match(reg)[1]}"
    number.to_f
  end

  def self.fetch
    response = Faraday.new.get 'https://www.santander.com.ar/ConectorPortalStore/Rendimiento'
    html = Nokogiri::HTML(response.body)

    desired_items = [
      'SUPER AHORRO $ CUOTA A',
      'SUPER AHORRO PLUS CUOTA A',
      'SUPERGESTION MIX VI CUOTA A'
    ]

    list = []

    html.css('tr').each do |row|
      row_description = row.css('table tr td').text

      # ignore items that doesn't contain desired_items
      next unless desired_items.any? { |i| row_description.include?(i) }

      item_entry = {
        name: row_description.strip,
        value: FciHelper.format_number(row.css('td')[3].text),
        last_day: FciHelper.format_number(row.css('td')[4].text),
        last_30_days: FciHelper.format_number(row.css('td')[5].text),
        last_90_days: FciHelper.format_number(row.css('td')[6].text),
        last_12_months: FciHelper.format_number(row.css('td')[7].text)
      }

      list << item_entry
    end

    list
  end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/unit_trust_entries_helper.rb
module UnitTrustEntriesHelper
end

app/helpers/unit_trusts_helper.rb
module UnitTrustsHelper
  def self.deposit_time_badge(time)
    case time
    when 0
      '<span class="badge badge-soft-success">Inmediato</span>'
    when 1..24
      "<span class=\"badge badge-soft-info\">#{time} horas</span>"
    when 25..48
      "<span class=\"badge badge-soft-warning\">#{time} horas</span>"
    else
      "<span class=\"badge badge-soft-danger\">#{time} horas</span>"
    end
  end
end

app/views/fci/all.html.erb
<h1>Fondos Santander</h1>
<p>Última actualización: <%= @last_update %>

<table>
  <tr>
    <td>Nombre</td>
    <td>Valor</td>
    <td>Var. diaria</td>
    <td>Últimos 30 días</td>
    <td>Últimos 90 días</td>
    <td>Últimos 12 meses</td>
  </tr>

  <% @list.each do |item| %>
  <tr>
    <td> <%=item.unit_trust.name %> </td>
    <td> <%=item.value %> </td>
    <td> <%=item.last_day %> </td>
    <td> <%=item.last_30_days %> </td>
    <td> <%=item.last_90_days %> </td>
    <td> <%=item.last_12_months %> </td>
  </tr>
  <%end%>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Santander</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@3.0.0-alpha"></script>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Libs CSS -->
    <link rel="stylesheet" href="/dashkit/assets/fonts/feather/feather.css" />
    <link rel="stylesheet" href="/dashkit/assets/libs/flatpickr/dist/flatpickr.min.css" />
    <link rel="stylesheet" href="/dashkit/assets/libs/quill/dist/quill.core.css" />
    <link rel="stylesheet" href="/dashkit/assets/libs/highlightjs/styles/vs2015.css" />

    <!-- Theme CSS -->
    <link rel="stylesheet" href="/dashkit/assets/css/theme.min.css">

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body>
    <div class="main-content">
      <div class="container-fluid">
        <div class="row justify-content-center">
          <div class="col-12 col-lg-10 col-xl-8">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <!-- Libs JS -->
    <script src="/dashkit/assets/libs/jquery/dist/jquery.min.js"></script>
    <script src="/dashkit/assets/libs/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="/dashkit/assets/libs/@shopify/draggable/lib/es5/draggable.bundle.legacy.js"></script>
    <script src="/dashkit/assets/libs/autosize/dist/autosize.min.js"></script>
    <!-- <script src="/dashkit/assets/libs/chart.js/dist/Chart.min.js"></script> -->
    <script src="/dashkit/assets/libs/dropzone/dist/min/dropzone.min.js"></script>
    <script src="/dashkit/assets/libs/flatpickr/dist/flatpickr.min.js"></script>
    <script src="/dashkit/assets/libs/highlightjs/highlight.pack.min.js"></script>
    <script src="/dashkit/assets/libs/jquery-mask-plugin/dist/jquery.mask.min.js"></script>
    <script src="/dashkit/assets/libs/list.js/dist/list.min.js"></script>
    <script src="/dashkit/assets/libs/quill/dist/quill.min.js"></script>
    <script src="/dashkit/assets/libs/select2/dist/js/select2.full.min.js"></script>
    <!-- <script src="/dashkit/assets/libs/chart.js/Chart.extension.js"></script> -->

    <!-- Theme JS -->
    <script src="/dashkit/assets/js/theme.min.js"></script>
    <script src="/dashkit/assets/js/dashkit.min.js"></script>
  </body>
</html>

app/views/site/about.html.erb
<div class="header mt-md-5">
  <div class="header-body">

    <!-- Pretitle -->
    <h6 class="header-pretitle">
      Sobre este sitio
    </h6>

    <!-- Title -->
    <h1 class="header-title">
      About
    </h1>
  </div>
</div>

<p style="margin-bottom:20px">El about de esta página te la debo.</p>
<p>Cualquier duda o comentario dejalo en el widget de abajo.</p>

<script async src="https://comments.app/js/widget.js?2" data-comments-app-website="KDS6Lz-O" data-limit="5"></script>

<p><%= link_to 'Volver a la home 🏠', "/" %></p>

app/views/site/disclaimer.html.erb
<div class="header mt-md-5">
  <div class="header-body">

    <!-- Pretitle -->
    <h6 class="header-pretitle">
      Yo te dije
    </h6>

    <!-- Title -->
    <h1 class="header-title">
      Disclaimer (aka #PUEDEFALLAR)
    </h1>

  </div>
</div>

<%= image_tag("disclaimer.gif") %>

<p class="mt-4"><i>"Esto es un proyecto personal, no trabajo para Santander y todo esto puede fallar."</i></p>
<p>Nadie debería invertir en un Fondo Común de Inversión sin antes:</p>
<ol>
  <li>Entender cómo funciona un FCI.</li>
  <li>Entender que hay riesgos, como en todas las inversiones.</li>
  <li>Entender que esta herramienta puede fallar (la hice en un fin de semana for god's sake).</li>
  <li>Entender que no estoy recomendando hacer estas inversiones.</li>
  <li>Entender que los retornos históricos no garantizan rendimientos futuros.</li>
  <li>Ya sos grande Roberto, no me hagas responsable por tus malas decisiones.</li>
  <li>Ver "Community" y "Rick & Morty", son 2 series increíbles.</li>
</ol>

<p><%= link_to 'Volver a la home 🏠', "/" %></p>

app/views/unit_trust_entries/_form.html.erb
<%= form_with(model: unit_trust_entry, local: true) do |form| %>
  <% if unit_trust_entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unit_trust_entry.errors.count, "error") %> prohibited this unit_trust_entry from being saved:</h2>

      <ul>
        <% unit_trust_entry.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value %>
  </div>

  <div class="field">
    <%= form.label :last_day %>
    <%= form.text_field :last_day %>
  </div>

  <div class="field">
    <%= form.label :last_30_days %>
    <%= form.text_field :last_30_days %>
  </div>

  <div class="field">
    <%= form.label :last_90_days %>
    <%= form.text_field :last_90_days %>
  </div>

  <div class="field">
    <%= form.label :last_12_months %>
    <%= form.text_field :last_12_months %>
  </div>

  <div class="field">
    <%= form.label :unit_trust_id %>
    <%= form.number_field :unit_trust_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unit_trust_entries/edit.html.erb
<h1>Editing Unit Trust Entry</h1>

<%= render 'form', unit_trust_entry: @unit_trust_entry %>

<%= link_to 'Show', @unit_trust_entry %> |
<%= link_to 'Back', unit_trust_entries_path %>

app/views/unit_trust_entries/index.html.erb
<div class="header mt-md-5">
  <div class="header-body">
    <h1 class="header-title">Unit Trust Entries</h1>
  </div>
</div>

<div class="alert alert-primary" role="alert" id="notice" style="display: <%= "none" if notice.blank? %>">
  <%= notice %>
</div>

<div class="card">
  <div class="table-responsive mb-0">
    <table class="table table-sm table-nowrap card-table">
      <thead>
        <tr>
          <th>Date</th>
          <th>Value</th>
          <th>Last day</th>
          <th>Last 30 days</th>
          <th>Last 90 days</th>
          <th>Last 12 months</th>
          <th>Unit trust</th>
          <th colspan="3"></th>
        </tr>
      </thead>
      <tbody>
        <% @unit_trust_entries.each do |unit_trust_entry| %>
          <tr>
            <td><%= unit_trust_entry.date %></td>
            <td><%= unit_trust_entry.value %></td>
            <td><%= unit_trust_entry.last_day %></td>
            <td><%= unit_trust_entry.last_30_days %></td>
            <td><%= unit_trust_entry.last_90_days %></td>
            <td><%= unit_trust_entry.last_12_months %></td>
            <td><%= unit_trust_entry.unit_trust_id %></td>
            <td><%= link_to 'Show', unit_trust_entry %></td>
            <td><%= link_to 'Edit', edit_unit_trust_entry_path(unit_trust_entry) %></td>
            <td><%= link_to 'Destroy', unit_trust_entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Unit Trust Entry', new_unit_trust_entry_path, { :class=>"btn btn-primary lift" } %>
<%= link_to 'Fetch', '/unit_trust_entries/fetch', { :class=>"btn btn-secondary lift" } %>

app/views/unit_trust_entries/new.html.erb
<h1>New Unit Trust Entry</h1>

<%= render 'form', unit_trust_entry: @unit_trust_entry %>

<%= link_to 'Back', unit_trust_entries_path %>

app/views/unit_trust_entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @unit_trust_entry.date %>
</p>

<p>
  <strong>Value:</strong>
  <%= @unit_trust_entry.value %>
</p>

<p>
  <strong>Last day:</strong>
  <%= @unit_trust_entry.last_day %>
</p>

<p>
  <strong>Last 30 days:</strong>
  <%= @unit_trust_entry.last_30_days %>
</p>

<p>
  <strong>Last 90 days:</strong>
  <%= @unit_trust_entry.last_90_days %>
</p>

<p>
  <strong>Last 12 months:</strong>
  <%= @unit_trust_entry.last_12_months %>
</p>

<p>
  <strong>Unit trust:</strong>
  <%= @unit_trust_entry.unit_trust_id %>
</p>

<%= link_to 'Edit', edit_unit_trust_entry_path(@unit_trust_entry) %> |
<%= link_to 'Back', unit_trust_entries_path %>

app/views/unit_trusts/_form.html.erb
<div class="card">
  <div class="card-body">
    <%= form_with(model: unit_trust, local: true) do |form| %>
      <% if unit_trust.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(unit_trust.errors.count, "error") %> prohibited this unit_trust from being saved:</h2>

          <ul>
            <% unit_trust.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name %>
      </div>

      <div class="field">
        <%= form.label :description %>
        <%= form.text_area :description %>
      </div>

      <div class="field">
        <%= form.label :deposit_time %>
        <%= form.text_field :deposit_time %>
      </div>

      <div class="field">
        <%= form.label :color %>
        <%= form.text_field :color %>
      </div>

      <div class="actions">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/unit_trusts/edit.html.erb
<h1>Editing Unit Trust</h1>

<%= render 'form', unit_trust: @unit_trust %>

<%= link_to 'Show', @unit_trust %> |
<%= link_to 'Back', unit_trusts_path %>

app/views/unit_trusts/index.html.erb
<div class="header mt-md-5">
  <div class="header-body">
    <h1 class="header-title">Unit Trusts</h1>
  </div>
</div>

<div class="alert alert-primary" role="alert" id="notice" style="display: <%= "none" if notice.blank? %>">
  <%= notice %>
</div>

<div class="card">
  <div class="table-responsive mb-0">
    <table class="table table-sm table-nowrap card-table">
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @unit_trusts.each do |unit_trust| %>
          <tr>
            <td><%= unit_trust.name %></td>
            <td><%= link_to 'Show', unit_trust %></td>
            <td><%= link_to 'Edit', edit_unit_trust_path(unit_trust) %></td>
            <td><%= link_to 'Destroy', unit_trust, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<%= link_to 'New Unit Trust', new_unit_trust_path, { :class=>"btn btn-primary lift" } %>

app/views/unit_trusts/new.html.erb
<div class="header mt-md-5">
  <div class="header-body">
    <h1 class="header-title">New Unit Trust</h1>
  </div>
</div>

<%= render 'form', unit_trust: @unit_trust %>

<%= link_to 'Back', unit_trusts_path %>

app/views/unit_trusts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @unit_trust.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @unit_trust.description %>
</p>

<p>
  <strong>Deposit Time:</strong>
  <%= @unit_trust.deposit_time %>
</p>

<p>
  <strong>Color:</strong>
  <%= @unit_trust.color %>
</p>

<%= link_to 'Edit', edit_unit_trust_path(@unit_trust) %> |
<%= link_to 'Back', unit_trusts_path %>

app/views/utf/all.html.erb
<div class="header mt-md-5">
  <div class="header-body">

    <!-- Pretitle -->
    <h6 class="header-pretitle">
      Última actualización: <%= @last_update %>
    </h6>

    <!-- Title -->
    <h1 class="header-title">
      Fondos Santander
    </h1>

  </div>
</div>

<div class="card">
  <div class="table-responsive mb-0">
    <table class="table table-sm table-nowrap card-table">
      <thead>
        <tr>
          <th>Nombre</th>
          <th>Acredit.</th>
          <th>Valor</th>
          <th>
            Var. <br/>
            Diaria
          </th>
          <th>
            Últimos <br/>
            30 días
          </th>
          <th>
            Últimos <br />
            90 días
          </th>
          <th>
            Últimos <br />
            12 meses
          </th>
        </tr>
      </thead>
      <tbody>
        <% @list.each do |item| %>
        <tr>
          <td>
            <span>
              <%= link_to item.unit_trust.name, "detail/#{item.unit_trust.id}" %>
            </span>
          </td>
          <td> <%=UnitTrustsHelper.deposit_time_badge(item.unit_trust.deposit_time).html_safe %> </td>
          <td> <%=item.value %> </td>
          <td> <%=item.last_day %> </td>
          <td> <%=item.last_30_days %> </td>
          <td> <%=item.last_90_days %> </td>
          <td> <%=item.last_12_months %> </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <h4 class="card-header-title">Variación Diaria</h4>
  </div>
  <div class="card-body">
    <canvas id="chart" height="100" width="400" class="chart-canvas"></canvas>
  </div>
</div>

<script>
  var ctx = document.getElementById('chart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'line',
    options: {},
    data: {
      labels: <%= raw @graph_data.first[:dates].map {|i| i.to_s } %>,
      datasets: [
      <% @graph_data.each do |item| %>
      {
        label: "<%= item[:name] %>",
        fill: false,
        borderColor: "#<%= item[:color] %>",
        backgroundColor: "#<%= item[:color] %>",
        data: <%= item[:values] %>
      },
      <%end%>
      ]
    }
  });
</script>

<p class="text-muted">
  Los valores se toman de la <%= link_to 'página de Santander', 'https://www.santander.com.ar/banco/online/personas/inversiones/super-fondos/rendimientos' %>
</p>

<p class="text-muted">
  Hecho por <%= link_to 'betzerra', 'https://www.betzerra.com/website-con-los-valores-historicos-de-los-fci-del-banco-santander/' %> con ❤️ y <%= link_to 'Ruby on Rails', 'https://rubyonrails.org' %>.
</p>

<p class="text-muted">Por favor, lee mi <%= link_to 'disclaimer', 'disclaimer' %>.</p>

app/views/utf/detail.html.erb
<div class="header mt-5">
  <div class="header-body">
    <h1 class="header-title">
      <%= @unit_trust.name %>
    </h1>

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page"><%= link_to "Home", "/" %></li>
        <li class="breadcrumb-item active" aria-current="page"><%= @unit_trust.name %></li>
      </ol>
    </nav>
  </div>
</div>

<div class="card">
  <div class="card-header">
    <h4 class="card-header-title">Descripción</h4>
  </div>
  <div class="card-body">
    <div class="list-group list-group-flush">
      <div class="list-group-item">
        <%= @unit_trust.description %>
      </div>
      <div class="list-group-item">
        <div class="row">
          <div class="col">
            Plazo de acreditación:
          </div>
          <div class="col-auto text-muted">
            <%=UnitTrustsHelper.deposit_time_badge(@unit_trust.deposit_time).html_safe %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <canvas id="chart" height="100" width="400" class="chart-canvas"></canvas>
  </div>
</div>

<script>
  var ctx = document.getElementById('chart').getContext('2d');
  var chart = new Chart(ctx, {
    type: 'line',
    options: {
      legend: {
        display: false
      }
    },
    data: {
        labels: <%= raw @graph_data.map { |i| i.date.to_s } %>,
        datasets: [{
            borderColor: "#<%= @unit_trust.color %>",
            backgroundColor: "#<%= @unit_trust.color %>",
            data: <%= @graph_data.map { |i| i.value } %>
        }]
    }
  });
</script>

<div class="card">
  <div class="table-responsive mb-0">
    <table class="table table-sm table-nowrap card-table">
      <thead>
        <tr>
          <th>Fecha</th>
          <th>Valor</th>
          <th>Var. Diaria</th>
          <th>Últimos 30 días</th>
          <th>Últimos 90 días</th>
          <th>Últimos 12 meses</th>
        </tr>
      </thead>
      <tbody>
        <% @list.each do |item| %>
        <tr>
          <th scope="row"> <%=item.date %> </th>
          <td> <%=item.value %> </td>
          <td> <%=item.last_day %> </td>
          <td> <%=item.last_30_days %> </td>
          <td> <%=item.last_90_days %> </td>
          <td> <%=item.last_12_months %> </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
</div>